# This workflow will build a Java project with Maven when a tag is pushed
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
---
name: Java CI with Maven
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file: :
        distribution: 'zulu'
    - name: 'Create settings.xml'
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        servers: '[{"id": "github-dp3t-shared", "username": "${{ github.actor }}", "password": "${{ github.token}}"}]'
        repositories: '[{"id" : "github-dp3t-shared", "url" : "https://maven.pkg.github.com/DP-3T/dp3t-shared-backend"}]'
    - name: Build with Maven
      run: |
        mvn install --file dpppt-additionalinfo-backend/pom.xml;
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TESTCONTAINERS_RYUK_DISABLED: true
    - name: shasum
      run: shasum -a 256 dpppt-additionalinfo-backend/target/dpppt-additionalinfo-backend.jar > dpppt-additionalinfo-backend/target/dpppt-additionalinfo-backend.jar.sha256
      shell: bash
    - name: "Create new release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dpppt-additionalinfo-backend/target/dpppt-additionalinfo-backend.jar
          dpppt-additionalinfo-backend/target/dpppt-additionalinfo-backend.jar.sha256
